"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Sparkles, Copy, Check } from "lucide-react";

export default function LLMReport({ text }) {
  const [copied, setCopied] = useState(false);

  if (!text) {
    return (
      <div className="bg-zinc-900/90 border border-orange-500/30 rounded-xl p-8 text-center">
        <p className="text-gray-500">No report available</p>
      </div>
    );
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-zinc-900/90 border-2 border-orange-500/30 rounded-xl overflow-hidden"
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-orange-500/20">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-orange-500" />
          <h3 className="font-bold text-orange-400">AI Security Report</h3>
        </div>
        
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={handleCopy}
          className="flex items-center gap-1 text-sm text-orange-400 hover:text-orange-300"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4" />
              <span>Copied!</span>
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              <span>Copy</span>
            </>
          )}
        </motion.button>
      </div>

      {/* Content */}
      <div className="p-4 max-h-[400px] overflow-y-auto custom-scrollbar">
        <pre className="text-sm text-gray-300 whitespace-pre-wrap font-sans leading-relaxed">
          {text}
        </pre>
      </div>

      {/* Footer */}
      <div className="p-3 border-t border-orange-500/20 bg-black/30 text-center">
        <p className="text-xs text-gray-500">
          Generated by LLM • Analysis complete
        </p>
      </div>

      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: rgba(249, 115, 22, 0.1);
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #f97316;
          border-radius: 2px;
        }
      `}</style>
    </motion.div>
  );
}